const ASSETS = {
  pork: { key:'pork', label:'五花肉', dish:'烤五花肉飯', need:3, raw:'./assets/pork_raw.png?v=4', half:'./assets/pork_half.png?v=4', perfect:'./assets/pork_perfect.png?v=4', burnt:'./assets/pork_burnt.png?v=5', bento:'./assets/pork_bento.png', icon:'./assets/pork_raw.png?v=4', size:{w:188,h:131}, positions:[{x:24,y:74,r:-8},{x:128,y:70,r:2},{x:232,y:74,r:8}], time:{half:2.0,flip:2.5,perfectStart:4.1,perfectEnd:6.3,burn:7.4}},
  chicken: { key:'chicken', label:'雞腿排', dish:'烤雞腿飯', need:1, raw:'./assets/chicken_raw.png?v=3', perfect:'./assets/chicken_perfect.png?v=3', burnt:'./assets/chicken_burnt.png?v=3', bento:'./assets/chicken_bento.png', icon:'./assets/chicken_raw.png?v=3', size:{w:360,h:327}, positions:[{x:24,y:55,r:0}], time:{half:3.5,flip:4.2,perfectStart:6.3,perfectEnd:9.1,burn:10.5}},
  loin: { key:'loin', label:'里肌肉', dish:'烤里肌肉飯', need:3, raw:'./assets/loin_raw.png?v=3', perfect:'./assets/loin_perfect.png?v=3', burnt:'./assets/loin_burnt.png?v=3', bento:'./assets/loin_bento.png', icon:'./assets/loin_raw.png?v=3', size:{w:228,h:345}, positions:[{x:38,y:88,r:-15},{x:138,y:82,r:-12},{x:238,y:88,r:-15}], time:{half:1.6,flip:2.3,perfectStart:3.3,perfectEnd:5.0,burn:6.2}},
  rib: { key:'rib', label:'排骨', dish:'烤排骨飯', need:3, raw:'./assets/rib_raw.png?v=3', perfect:'./assets/rib_perfect.png?v=3', burnt:'./assets/rib_burnt.png?v=3', bento:'./assets/rib_bento.png', icon:'./assets/rib_raw.png?v=3', size:{w:180,h:186}, positions:[{x:22,y:98,r:-7},{x:126,y:92,r:1},{x:230,y:98,r:7}], time:{half:2.6,flip:3.2,perfectStart:5.0,perfectEnd:7.8,burn:9.0}}
};
const orderKeys = ['pork','chicken','loin','rib'];
let currentIndex=0, current=ASSETS.pork, cooked=0, pieces=[], runningTimer=null, score=0, tickets=0, combo=0;
const $=id=>document.getElementById(id);
const screens={home:$('screen-home'),game:$('screen-game'),result:$('screen-result')};
function showScreen(name){Object.values(screens).forEach(s=>s.classList.remove('active'));screens[name].classList.add('active'); if(name==='game'&&typeof fitGame==='function') fitGame()}
function toast(text){const t=$('toast');t.textContent=text;t.style.display='block';clearTimeout(t._timer);t._timer=setTimeout(()=>t.style.display='none',1700)}
function showFeedback(type){const el=$('fbLabel');if(!el)return;const map={perfect:'./assets/fb_perfect.png',good:'./assets/fb_good.png',combo:'./assets/fb_combo.png',super:'./assets/fb_super.png'};el.src=map[type]||map.good;el.classList.remove('show');void el.offsetWidth;el.classList.add('show')}
function setOrder(key){current=ASSETS[key]; cooked=0; pieces=[]; combo=0; {const oc=document.querySelector('.order-card'); if(oc) oc.dataset.meat=key; const bb=document.querySelector('.bento-box'); if(bb) bb.dataset.meat=key;} $('orderName').textContent=current.dish; $('progressText').textContent=`0 / ${current.need}`; $('hintText').textContent='肉放上烤網後會開始變色，看到「返せ」請翻面。'; const need=$('needIcons'); need.innerHTML=''; {const im=document.createElement('img'); im.src=current.icon; need.appendChild(im)} document.querySelectorAll('.meat-tab').forEach(btn=>btn.classList.toggle('active',btn.dataset.meat===key)); resetBento(); renderPieces()}
function resetBento(){ $('bentoMeatSlot').innerHTML='' }
function renderPieces(){const layer=$('meatLayer'); layer.innerHTML=''; layer.className='meat-layer meat-'+current.key; clearInterval(runningTimer); const _n=current.positions.length; const _rb=current.positions.map((_,i)=>0.78+(_n>1?i/(_n-1):0.5)*0.5); for(let _i=_rb.length-1;_i>0;_i--){const _j=Math.floor(Math.random()*(_i+1)); const _t=_rb[_i]; _rb[_i]=_rb[_j]; _rb[_j]=_t;} current.positions.forEach((pos,i)=>{const img=document.createElement('img'); img.className='meat-piece'; img.src=current.raw; img.style.width=current.size.w+'px'; img.style.height=current.size.h+'px'; img.style.left=pos.x+'px'; img.style.top=pos.y+'px'; img.style.transform=`rotate(${pos.r}deg)`; img.dataset.index=i; const piece={el:img,elapsed:Math.random()*0.5,flipped:false,done:false,burned:false,state:'raw',baseRotate:pos.r,rate:+(_rb[i]+(Math.random()-0.5)*0.12).toFixed(3)}; img.addEventListener('click',()=>flipPiece(piece)); layer.appendChild(img); pieces.push(piece)}); startCooking()}
function startCooking(){runningTimer=setInterval(()=>{const fireSpeed=Number($('fireRange').value); const speed=fireSpeed===1?0.055:fireSpeed===2?0.085:0.125; let maxProgress=0; pieces.forEach(piece=>{if(piece.done||piece.burned)return; piece.elapsed+=speed*(piece.rate||1); updatePieceVisual(piece); maxProgress=Math.max(maxProgress,piece.elapsed/current.time.burn)}); $('heatPointer').style.setProperty('--prog',Math.min(100,maxProgress*100)+'%'); const needFlip=pieces.some(p=>!p.done&&!p.burned&&!p.flipped&&p.elapsed>=current.time.flip&&p.elapsed<current.time.perfectEnd); $('flipAlert').style.display=needFlip?'block':'none'},100)}
function updatePieceVisual(piece){const t=current.time; let st; if(piece.elapsed>=t.burn)st='burn'; else if(piece.elapsed>=t.perfectStart)st='perfect'; else if(piece.elapsed>=t.half)st='half'; else st='raw'; if(st===piece.state)return; piece.state=st; if(st==='burn'){if(!piece.burned)toast('烤焦了！這片不能出餐'); piece.burned=true; piece.el.src=current.burnt; piece.el.style.filter='drop-shadow(0 8px 10px #000)'; piece.el.style.opacity='.97'} else if(st==='perfect'){piece.el.src=current.perfect; piece.el.style.filter='drop-shadow(0 0 10px rgba(255,190,60,.55)) drop-shadow(0 8px 10px #000)'} else if(st==='half'){piece.el.src=current.half||current.raw; piece.el.style.filter=current.half?'drop-shadow(0 8px 10px #000)':'sepia(.35) saturate(1.2) brightness(.96) drop-shadow(0 8px 10px #000)'} else {piece.el.src=current.raw; piece.el.style.filter='drop-shadow(0 8px 10px #000)'}}
function flipPiece(piece){if(piece.done||piece.burned)return; if(piece.elapsed<current.time.flip-.5){toast('太早翻了，再等一下！'); return} piece.flipped=true; piece.el.style.transform=`rotate(${piece.baseRotate}deg) scaleX(-1)`; $('flipAlert').style.display='none'; toast('翻面成功！')}
function servePiece(){const perfect=pieces.find(p=>!p.done&&!p.burned&&p.flipped&&p.elapsed>=current.time.perfectStart&&p.elapsed<=current.time.perfectEnd); if(perfect){perfect.done=true; perfect.el.style.opacity='0'; cooked++; score+=100; combo++; showFeedback(combo>=3?'super':combo>=2?'combo':'perfect')} else {const good=pieces.find(p=>!p.done&&!p.burned&&p.flipped&&p.elapsed>=current.time.half&&p.elapsed<current.time.burn); if(!good){toast('還不能出餐：要翻面並接近完美熟度！'); return} good.done=true; good.el.style.opacity='0'; cooked++; score+=60; combo=0; showFeedback('good')} const slot=$('bentoMeatSlot'); const im=document.createElement('img'); im.src=current.perfect||current.bento; slot.innerHTML=''; slot.appendChild(im); $('progressText').textContent=`${cooked} / ${current.need}`; if(cooked>=current.need){clearInterval(runningTimer); tickets++; setTimeout(showResult,450)}}
function showResult(){ try{ sessionStorage.setItem('uenoDish', current.dish); }catch(e){} window.location.href='slot/index.html'; }
function nextOrder(){currentIndex=(currentIndex+1)%orderKeys.length; setOrder(orderKeys[currentIndex]); showScreen('game')}
$('startBtn').addEventListener('click',()=>{currentIndex=0; setOrder(orderKeys[currentIndex]); showScreen('game')}); {const rb=$('restartBtn'); if(rb) rb.addEventListener('click',()=>{currentIndex=0; score=0; tickets=0; combo=0; setOrder(orderKeys[0]); toast('重新開始！');});} $('serveBtn').addEventListener('click',servePiece); $('nextBtn').addEventListener('click',nextOrder); document.querySelectorAll('.meat-tab').forEach(btn=>btn.addEventListener('click',()=>{const key=btn.dataset.meat; currentIndex=orderKeys.indexOf(key); setOrder(key)})); $('howBtn').addEventListener('click',()=>alert('玩法：看到「返せ」點肉翻面，進入完美熟度時按「夾進便當盒」。完成訂單可得抽獎券。')); $('soundBtn').addEventListener('click',()=>toast('預覽版尚未加入音效，正式版可加入滋滋聲、出餐叮聲。'));

// 操作畫面：把 941×1672 背景畫布等比縮放置中（四周黑邊）
function fitGame(){const g=document.getElementById('screen-game'); if(!g) return; const pad=24; g.style.setProperty('--gfit', Math.min((window.innerWidth-pad)/941, (window.innerHeight-pad)/1672));}
window.addEventListener('resize',fitGame); window.addEventListener('orientationchange',fitGame); fitGame();

// 背景音樂（無限循環）
(function(){
  const bgm=$('bgm'), muteBtn=$('muteBtn');
  if(!bgm) return;
  let started=false;
  const muted=()=>localStorage.getItem('uenoMute')==='1';
  function icon(){ if(muteBtn) muteBtn.textContent=(muted()||bgm.paused)?'🔇':'🔊'; }
  function start(){ if(muted()){icon();return;} bgm.volume=0.45; const p=bgm.play(); if(p&&p.then){ p.then(()=>{started=true;icon();}).catch(()=>{}); } else { started=true; icon(); } }
  if(muteBtn){ muteBtn.addEventListener('click',(e)=>{ e.stopPropagation(); if(bgm.paused){ localStorage.removeItem('uenoMute'); bgm.volume=0.45; bgm.play().catch(()=>{}); started=true; } else { bgm.pause(); localStorage.setItem('uenoMute','1'); } icon(); }); }
  const sb=$('startBtn'); if(sb) sb.addEventListener('click',start);
  document.addEventListener('click',()=>{ if(!started && !muted()) start(); });
  document.addEventListener('touchstart',()=>{ if(!started && !muted()) start(); },{passive:true});
  icon();
})();
